version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: globule-ollama
    ports:
      - "11434:11434"
    volumes:
      - C:\Users\18312\.ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ollama-data: