version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: globule-ollama
    ports:
      - "11434:11434"
    volumes:
      - C:\Users\18312\.ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:11434/api/tags || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 120s

volumes:
  ollama-data: